### ISSUE TITLE
Incorrect url submitted to Odin Project

### ISSUE THREAD

**Issue by Dubsta** [unoriginalNameCS/odin-recipes#1]
Looks like you've submitted the wrong live preview URL to the Odin Project.

I can see your pages have been published on github pages, but from within the Odin Project, when clicking on "Live Preview" the URL doesn't work. 

Apart from that, pages look good :)

![image](https://github.com/unoriginalNameCS/odin-recipes/assets/8635653/5f24b2c5-dfaa-4711-9d6f-f026b3bff3f1)

**Comment by unoriginalNameCS** [comment]
Hi,
Thanks for the feedback :). I edited the URL for live preview in the submission.
